# HARJOITUS 1

In [2]:
## Harjoitus 1. Pandas-kirjasto ja maailman kaupungit.
# Aineisto: https://simplemaps.com/data/world-cities
# Asenna Pandas-kirjasto, ja tutustu sen toimintaan. Kirjoita Python-koodia, joka hyödyntää Pandas-kirjastoa.
# Lataa kirjaston avulla CSV-aineisto (https://simplemaps.com/data/world-cities) muistiin ja selvitä miten teet seuraavat:
# a. Listaa kymmenen suurinta kaupunkia.
# b. Listaa kaupungit, joissa on yli 500t mutta alle 1M asukasta.

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("worldcities.csv")

In [5]:
df.columns

Index(['city', 'city_ascii', 'lat', 'lng', 'country', 'iso2', 'iso3',
       'admin_name', 'capital', 'population', 'id'],
      dtype='object')

In [6]:
harjoitus_a = df.sort_values(by=['population'],ascending=False).head(10)
harjoitus_a

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629
5,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,24922000.0,1608618140
6,Shanghai,Shanghai,31.1667,121.4667,China,CN,CHN,Shanghai,admin,24073000.0,1156073548
7,São Paulo,Sao Paulo,-23.5500,-46.6333,Brazil,BR,BRA,São Paulo,admin,23086000.0,1076532519
8,Seoul,Seoul,37.5600,126.9900,South Korea,KR,KOR,Seoul,primary,23016000.0,1410836482
9,Mexico City,Mexico City,19.4333,-99.1333,Mexico,MX,MEX,Ciudad de México,primary,21804000.0,1484247881

In [7]:
harjoitus_a["city"]

0          Tokyo
1        Jakarta
2          Delhi
3      Guangzhou
4         Mumbai
5         Manila
6       Shanghai
7      São Paulo
8          Seoul
9    Mexico City
Name: city, dtype: object

In [8]:
harjoitus_b = df[(500000 < df['population']) & ( df['population']< 1000000)]
harjoitus_b

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
757,Port-au-Prince,Port-au-Prince,18.5333,-72.3333,Haiti,HT,HTI,Ouest,primary,987310.0,1332401940
768,Kathmandu,Kathmandu,27.7172,85.3240,Nepal,NP,NPL,NaN,primary,975453.0,1524589448
769,Ottawa,Ottawa,45.4247,-75.6950,Canada,CA,CAN,Ontario,primary,989567.0,1124399363
770,Lilongwe,Lilongwe,-13.9833,33.7833,Malawi,MW,MWI,Lilongwe,primary,989318.0,1454688499
771,Asmara,Asmara,15.3228,38.9250,Eritrea,ER,ERI,Ma’ĭkel,primary,963000.0,1232791236
...,...,...,...,...,...,...,...,...,...,...,...
1546,Kimberley,Kimberley,-28.7383,24.7639,South Africa,ZA,ZAF,Northern Cape,admin,500757.0,1710282622
1547,Jammu,Jammu,32.7300,74.8700,India,IN,IND,Jammu and Kashmīr,admin,502197.0,1356491738
1550,Ile-Ife,Ile-Ife,7.4667,4.5667,Nigeria,NG,NGA,Osun,minor,501952.0,1566756897
1552,Kirov,Kirov,58.6000,49.6500,Russia,RU,RUS,Kirovskaya Oblast’,admin,501468.0,1643106064
1554,Meicheng,Meicheng,30.6412,116.5689,China,CN,CHN,Anhui,minor,500292.0,1156136207

In [9]:
harjoitus_b ["city"].unique()

array(['Port-au-Prince', 'Kathmandu', 'Ottawa', 'Lilongwe', 'Asmara',
       'Freetown', 'Vientiane', 'Jerusalem', 'Riga', 'Bangui', 'Dushanbe',
       'Lomé', 'Ashgabat', 'Zagreb', 'Libreville', 'Cotonou', 'Pretoria',
       'Vilnius', 'Winnipeg', 'Quebec City', 'Chisinau', 'Port Moresby',
       'Skopje', 'Djibouti', 'Gaza', 'Kingston', 'Rabat', 'San Salvador',
       'The Hague', 'Asunción', 'Juba', 'Maseru', 'Oklahoma City',
       'Xingcheng', 'Dongtai', 'Yingcheng', 'Chiba', 'Al Mijlad',
       'Pekanbaru', 'Luocheng', 'Dnipro', 'Danyang', 'Godē', 'Natal',
       'Nada', 'Zamboanga City', 'Kirkuk', 'Bridgeport', 'Naples',
       'Wuchuan', 'Huilong', 'Morelia', 'Málaga', 'Cebu City',
       'Al Manşūrah', 'Coimbatore', 'Santo Domingo Este', 'Setagaya',
       'Sŏngnam', 'Taishan', 'Teresina', 'Solāpur', 'Tangier',
       'Kermānshāh', 'Krasnodar', 'Baidoa', 'Gaalkacyo', 'Anqiu',
       'Feicheng', 'Seberang Jaya', 'El Alto', 'Kitakyūshū', 'Meishan',
       'Khartoum North', 'Kisangani', 'Aguascalientes', 'Marrakech',
       'Donetsk', 'Trujillo', 'New Orleans', 'Taihe', 'Trichinopoly',
       'Xin’an', 'Taihecun', 'Kashgar', 'Naucalpan de Juárez', 'Çankaya',
       'Santiago de Cuba', 'Owerri', 'Padang', 'Qingzhou', 'Lichuan',
       'Santiago del Estero', 'Daye', 'Hengzhou', 'Fort Worth',
       'Hartford', 'Esenyurt', 'Campo Grande', 'Zhuanghe',
       'Bobo-Dioulasso', 'Ad Dammām', 'Quzhou', 'Lhasa', 'Jiaozhou',
       'Bunia', 'Taguig City', 'Cancún', 'Mérida', 'Yangchun', 'Dengtalu',
       'Morādābād', 'Antipolo', 'Abeokuta', 'Bucheon', 'Zhoushan',
       'Tiruppūr', 'Chihuahua', 'Klang', 'As Sulaymānīyah', 'Gurgaon',
       'Turin', 'Tucson', 'Hai’an', 'Ar Ramādī', 'Laiyang', 'Sale',
       'Jalandhar', 'Marseille', 'Bucaramanga', 'Kaifeng Chengguanzhen',
       'Ikeja', 'Eskişehir', 'Saltillo', 'Gaomi', 'Liverpool', 'Ipoh',
       'Oran', 'Portsmouth', 'Southampton', 'Hermosillo', 'Cochabamba',
       'Weichanglu', 'Shache', 'Wuxi', 'Leping', 'Hailun', 'Macheng',
       'Akure', 'Ilorin', 'Yuci', 'Saratov', 'Erbil', 'Iguaçu',
       'Pasig City', 'Dehui', 'Kālkāji Devi', 'Bhubaneshwar', 'Honolulu',
       'Tongchuan', 'Cheongju', 'Chengxiang', 'Thessaloníki', 'Warri',
       'Sakai', 'Pointe-Noire', 'Rongjiawan', 'Mediouna', 'Butterworth',
       'Renqiu', 'Xindi', 'Bhayandar', 'Wu’an', 'São Bernardo do Campo',
       'Māndvi', 'Barinas', 'Zijinglu', 'Gaoyou', 'Culiacán', 'Hejian',
       'Yiyang', 'Puxi', 'Androtsy', 'McAllen', 'Qingping', 'Omaha',
       'João Pessoa', 'Dongyang', 'Querétaro', 'Kraków', 'George Town',
       'Abaeté', 'Palermo', 'Valencia', 'Xigazê', 'El Paso', 'Seyhan',
       'Niigata', 'Hempstead', 'Leeds', 'Hamamatsu', 'Bağcılar',
       'Xiangxiang', 'Bilbao', 'Chaohucun', 'Fuyang', 'Homs',
       'Küçükçekmece', 'Lubango', 'Zouping', 'Khŭjand', 'San Luis Potosí',
       'Nottingham', 'Cencheng', 'Dali', 'Hamhŭng', 'Korla', 'Rājshāhi',
       'Erzurum', 'Frankfurt', 'Al ‘Ayn', 'Songzi', 'Albuquerque',
       'Patiāla', 'Laixi', 'Bahawalpur', 'Zhongba', 'Kaduna', 'Qingnian',
       'San Pedro Sula', 'Qamdo', 'Xinhualu', 'Nerima', 'Guangshui',
       'Pietermaritzburg', 'Baardheere', 'Tlajomulco de Zúñiga',
       'Samarinda', 'Changhua', 'Sizhan', 'Ciudad Guayana', 'Cúcuta',
       'Dhūlia', 'Burco', 'Licheng', 'Ōta-ku', 'Thiruvananthapuram',
       'Tyumen', 'Nampula', 'Zaporizhzhia', 'Kyaukse', 'Chengguan',
       'Kumamoto', 'Nehe', 'Osogbo', 'Cabinda', 'Kermān', 'Zunhua',
       'Rochester', 'Valenzuela', 'Orūmīyeh', 'Wugang', 'Shuangqiao',
       'Tshikapa', 'São José dos Campos', 'Comodoro Rivadavia',
       'Cagayan de Oro', 'Tondo', 'Langzhong', 'Qian’an', 'Lviv',
       'Sarasota', 'Reynosa', 'Santo André', 'An Najaf', 'Sagamihara',
       'Guli', 'Mississauga', 'Concepción', 'Okayama', 'Anlu', 'Mwanza',
       'Fresno', 'Changsha', 'Torreón', 'Shihezi', 'Enugu', 'Jaboatão',
       'Tulsa', 'Yanggok', 'Yatou', 'Edogawa', 'Allentown',
       'Ribeirão Prêto', 'Xichang', 'Latakia', 'Bhiwandi',
       'City of Parañaque', 'Dasmariñas', 'Dayton', 'Sahāranpur',
       'Warangal', 'Soledad', 'Osasco', 'Dashiqiao', 'Birmingham',
       'Nampo', 'Shiliguri', 'Banjarmasin', 'Sha Tin', 'Salem',
       'General Santos', 'Cocody', 'Ḩamāh', 'Pendik', 'Bacoor', 'Vellore',
       'Shishi', 'Guadalupe', 'Adachi', 'Qianxi', 'Tolyatti', 'Macau',
       'Bauchi', 'Hamilton', 'Łódź', 'Miluo Chengguanzhen', 'Gaizhou',
       'Karbalā’', 'Leling', 'Jianshe', 'Shizuoka', 'Charleston',
       'Jingcheng', 'Kochi', 'Mar del Plata', 'Cape Coral', 'Tasikmalaya',
       'Rasht', 'Xinmin', 'Shanhu', 'Zhongshu', 'Gorakhpur', 'Zaragoza',
       'Wrocław', 'Acapulco de Juárez', 'Bahār', 'Kumul', 'Murcia',
       'Pinghu', 'Guankou', 'Tlaquepaque', 'Songyang', 'Ch’ŏngjin',
       'Puyang Chengguanzhen', 'Qionghu', 'Zhaodong', 'Narela', 'Huambo',
       'Wenchang', 'Villavicencio', 'Shulan', 'Tlalnepantla',
       'Catia La Mar', 'Sargodha', 'Al Hufūf', 'Durango', 'Jalingo',
       'Bouaké', 'Mazatlán', 'San Jose del Monte', 'Ansan',
       'Abomey-Calavi', 'Lingbao Chengguanzhen', 'Hwasu-dong',
       'Sialkot City', 'Huế', 'Bulawayo', 'Xiping', 'Sanhe', 'Ch’ŏnan',
       'Contagem', 'Jieshou', 'Selçuklu', 'Ērer Sātā', 'Honchō',
       'Düsseldorf', 'Izhevsk', 'Guntūr', 'Guixi', 'Sorocaba', 'Yıldırım',
       'Petaling Jaya', 'Tengyue', 'Wuxue', 'Rasūlpur', 'Bhāvnagar',
       'Brahmapur', 'Qufu', 'Gaobeidian', 'Ruiming', 'Columbia',
       'Concord', 'Noida', 'Gold Coast', 'Xinshi', 'Ta‘izz', 'Aracaju',
       'Jeonju', 'Bhāngar', 'Jin’e', 'Barnaul', 'Makati City',
       'Rotterdam', 'Changping', 'Benghazi', 'Kryvyi Rih', 'Ḩalwān',
       'Colorado Springs', 'Suohe', 'Chimalhuacán', 'Xinxing', 'Bhilai',
       'Mangalore', 'Port-Bouët', 'Zhuangyuan', 'Glasgow', 'Namangan',
       'Ulyanovsk', 'Tân An', 'Irkutsk', 'Nāgercoil', 'Jos', 'Pontianak',
       'Bazhou', 'Turpan', 'Villa Nueva', 'Las Piñas City', 'Springfield',
       'Knoxville', 'Meihekou', 'Jurong', 'Feira de Santana',
       'Khabarovsk', 'Zhugang', 'Leipzig', 'Xinji', 'Serang', 'Jambi',
       'Kandahār', 'San Miguel de Tucumán', 'Gothenburg', 'Yaroslavl',
       'Baton Rouge', 'Zhangshu', 'Vladivostok', 'Ogden', 'Kuantan',
       'Raurkela', 'Cuttack', 'Ar Rayyān', 'Haifa', 'Malanje', 'Bacolod',
       'Zhuozhou', 'Grand Rapids', 'Uberlândia', 'Albany', 'Tianchang',
       'Kawaguchi', 'Itabashi', 'Suginami-ku', 'Cimahi', 'Tuxtla',
       'Garoua', 'Ḩafr al Bāţin', 'Tumkūr', 'Balikpapan', 'Durban',
       'Kagoshima', 'Al Ḩillah', 'Makhachkala', 'Sihui', 'Irapuato',
       'Brampton', 'Mbale', 'Pereira', 'Bakersfield', 'Uvira', 'Dortmund',
       'Chuxiong', 'Mission Viejo', 'Zāhedān', 'New Haven', 'Shah Alam',
       'Wenlan', 'Cuiabá', 'Shangzhi', 'Essen', 'Botou', 'Mymensingh',
       'Anyang', 'Genoa', 'Durgāpur', 'Port Sudan', 'Al Mafraq',
       'Puente Alto', 'Dehra Dūn', 'Aţ Ţā’if', 'Wancheng', 'Hachiōji',
       'Xiulin', 'Fu’an', 'Tomsk', 'Tonalá', 'Juiz de Fora', 'Worcester',
       'Kolwezi', 'Chāpra', 'Bristol', 'Luofeng', 'Lingyuan', 'Irbid',
       'Al Maḩallah al Kubrá', 'Wencheng', 'Bremen', 'Ciudad Bolívar',
       'Orenburg', 'Shenzhou', 'Āsansol', 'Kuiju', 'Zhenzhou',
       'Surakarta', 'Dresden', 'Kolhāpur', 'Benguela', 'Ensenada',
       'Kemerovo', 'Lanxi', 'Dangyang', 'Farīdpur', 'Herāt', 'Luanzhou',
       'Hamadān', 'Novokuznetsk', 'Nellore', 'Palma', 'Chiclayo',
       'Nānded', 'Ajmer', 'Al Ḩudaydah', 'Kimhae', 'Provo', 'Rustenburg',
       'Amrāvati', 'Poznań', 'Huanghua', 'Muntinlupa City', 'Londrina',
       'Nansana', 'Tabūk', 'Heroica Matamoros', 'Akron', 'Samarkand',
       'Kaiyuan', 'Hannover', 'Valledupar', 'Fengcheng', 'Ixtapaluca',
       'Ghulja', 'City of Calamba', 'Ananindeua', 'Xiangyang', 'Fuding',
       'An Nāşirīyah', 'Ibagué', 'Ryazan', 'Kassala', 'Tripoli',
       'Chang’an', 'Kōtō-ku', 'Naberezhnyye Chelny', 'Aksu', 'Salta',
       'Astrakhan', 'Gulbarga', 'Cadaado', 'Lyon', 'Wuhai', 'Mingguang',
       'Antwerp', 'Yazd', 'Touba', 'Ardabīl', 'Bīkaner', 'Agartala',
       'Ndola', 'Himeji', 'Palm Bay', 'Tultitlán de Mariano Escobedo',
       'Ailan Mubage', 'Bandar ‘Abbās', 'Bắc Ninh', 'Ciudad Apodaca',
       'Santa Teresa del Tuy', 'Maipú', 'Penza', 'Soacha', 'Al Qaţīf',
       'Port Said', 'Loni', 'Yucheng', 'Sevastopol', 'Meknès', 'Mixco',
       'Arāk', 'Pohang', 'Longzhou', 'Anda', 'Jinghong', 'Sheffield',
       'Utsunomiya', 'Suez', 'Nuremberg', 'Surrey', 'Heshan', 'Ujjain',
       'Jiaji', 'Santa Marta', 'Joinvile', 'Beining', 'Des Moines',
       'Hải Dương', 'Carrefour', 'Maturín', 'Homyel’', 'Leicester',
       'Yanji', 'Macapá', 'Yicheng', 'Ulhāsnagar',
       'Al ‘Āshir min Ramaḑān', 'Lipetsk', 'Al ‘Amārah', 'Bhīlwāra',
       'Encheng', 'Murrieta', 'Aden', 'Kitwe', 'Matsuyama', 'Jhānsi',
       'Pingtung', 'Montería', 'Nagqu', 'Kimberley', 'Jammu', 'Ile-Ife',
       'Kirov', 'Meicheng'], dtype=object)

## TOINEN TAPA

In [10]:
for indeksi, rivi in df.iterrows():
    if rivi["population"] > 500000 and rivi["population"] < 1000000:
        print(rivi["city"], rivi["population"])

Port-au-Prince 987310.0
Kathmandu 975453.0
Ottawa 989567.0
Lilongwe 989318.0
Asmara 963000.0
Freetown 951000.0
Vientiane 948487.0
Jerusalem 919438.0
Riga 920643.0
Bangui 889231.0
Dushanbe 863400.0
Lomé 837437.0
Ashgabat 828100.0
Zagreb 809268.0
Libreville 797003.0
Cotonou 762000.0
Pretoria 741651.0
Vilnius 708203.0
Winnipeg 705244.0
Quebec City 705103.0
Chisinau 702300.0
Port Moresby 700000.0
Skopje 640000.0
Djibouti 603900.0
Gaza 590481.0
Kingston 580000.0
Rabat 572717.0
San Salvador 567698.0
The Hague 548320.0
Asunción 524190.0
Juba 525953.0
Maseru 519186.0
Oklahoma City 994284.0
Xingcheng 993000.0
Dongtai 990306.0
Yingcheng 986400.0
Chiba 981738.0
Al Mijlad 985000.0
Pekanbaru 983356.0
Luocheng 984100.0
Dnipro 980948.0
Danyang 980662.0
Godē 980782.0
Natal 980588.0
Nada 977700.0
Zamboanga City 977234.0
Kirkuk 975000.0
Bridgeport 975078.0
Naples 966144.0
Wuchuan 972400.0
Huilong 972525.0
Morelia 962555.0
Málaga 967250.0
Cebu City 964169.0
Al Manşūrah 960423.0
Coimbatore 959823.0
Santo Domingo Este 948855.0
Setagaya 940509.0
Sŏngnam 948757.0
Taishan 953900.0
Teresina 953172.0
Solāpur 951558.0
Tangier 947952.0
Kermānshāh 952285.0
Krasnodar 948827.0
Baidoa 950000.0
Gaalkacyo 950000.0
Anqiu 947723.0
Feicheng 946627.0
Seberang Jaya 946092.0
El Alto 943000.0
Kitakyūshū 935084.0
Meishan 936000.0
Khartoum North 936349.0
Kisangani 935977.0
Aguascalientes 934424.0
Marrakech 928850.0
Donetsk 929063.0
Trujillo 919899.0
New Orleans 925443.0
Taihe 924531.0
Trichinopoly 916857.0
Xin’an 920628.0
Taihecun 920471.0
Kashgar 920000.0
Naucalpan de Juárez 913681.0
Çankaya 914501.0
Santiago de Cuba 917340.0
Owerri 908109.0
Padang 914970.0
Qingzhou 914047.0
Lichuan 913700.0
Santiago del Estero 911506.0
Daye 909724.0
Hengzhou 908400.0
Fort Worth 908469.0
Hartford 907046.0
Esenyurt 891120.0
Campo Grande 906092.0
Zhuanghe 905852.0
Bobo-Dioulasso 903887.0
Ad Dammām 903312.0
Quzhou 902767.0
Lhasa 902500.0
Jiaozhou 900500.0
Bunia 900666.0
Taguig City 886722.0
Cancún 888797.0
Mérida 892363.0
Yangchun 891800.0
Dengtalu 887000.0
Morādābād 887871.0
Antipolo 887399.0
Abeokuta 888924.0
Bucheon 867678.0
Zhoushan 882932.0
Tiruppūr 877778.0
Natal 877662.0
Chihuahua 878062.0
Klang 878000.0
As Sulaymānīyah 878146.0
Gurgaon 876824.0
Turin 870952.0
Tucson 875284.0
Hai’an 874334.0
Ar Ramādī 874543.0
Laiyang 874127.0
Sale 850403.0
Jalandhar 873725.0
Marseille 870731.0
Bucaramanga 870752.0
Kaifeng Chengguanzhen 872000.0
Ikeja 861300.0
Eskişehir 871187.0
Saltillo 864431.0
Gaomi 868715.0
Liverpool 864122.0
Ipoh 866772.0
Oran 852000.0
Portsmouth 855679.0
Southampton 855569.0
Hermosillo 855563.0
Cochabamba 856198.0
Weichanglu 859424.0
Shache 851374.0
Wuxi 853197.0
Leping 852800.0
Hailun 850000.0
Macheng 849090.0
Akure 847903.0
Ilorin 847582.0
Yuci 840000.0
Saratov 845300.0
Erbil 846000.0
Iguaçu 844583.0
Pasig City 803159.0
Dehui 839786.0
Kālkāji Devi 824177.0
Bhubaneshwar 837737.0
Honolulu 835291.0
Tongchuan 834437.0
Cheongju 833276.0
Chengxiang 831113.0
Thessaloníki 824676.0
Warri 830106.0
Sakai 824408.0
Pointe-Noire 829134.0
Rongjiawan 826000.0
Mediouna 822851.0
Butterworth 821652.0
Renqiu 822455.0
Xindi 819446.0
Bhayandar 809378.0
Wu’an 819000.0
São Bernardo do Campo 816925.0
Māndvi 814655.0
Barinas 816264.0
Zijinglu 807857.0
Gaoyou 811800.0
Culiacán 808416.0
Hejian 810306.0
Yiyang 810447.0
Puxi 809535.0
Androtsy 809313.0
McAllen 809002.0
Qingping 797200.0
Omaha 806485.0
João Pessoa 801718.0
Dongyang 804398.0
Querétaro 801940.0
Kraków 800653.0
George Town 794313.0
Abaeté 800000.0
Palermo 800000.0
Valencia 792492.0
Xigazê 798153.0
El Paso 794344.0
Seyhan 792536.0
Niigata 790646.0
Hempstead 791018.0
Leeds 789194.0
Hamamatsu 788211.0
Bağcılar 734369.0
Xiangxiang 787216.0
Bilbao 775000.0
Chaohucun 782000.0
Fuyang 771000.0
Homs 775404.0
Küçükçekmece 770317.0
Lubango 776249.0
Zouping 774517.0
Khŭjand 770000.0
San Luis Potosí 772828.0
Nottingham 768638.0
Cencheng 772113.0
Dali 771128.0
Hamhŭng 768551.0
Korla 770000.0
Rājshāhi 763580.0
Erzurum 767848.0
Frankfurt 764104.0
Al ‘Ayn 766936.0
Songzi 765911.0
Albuquerque 765693.0
Patiāla 763280.0
Laixi 762900.0
Bahawalpur 762111.0
Zhongba 762140.0
Kaduna 760084.0
Qingnian 760781.0
San Pedro Sula 760182.0
Qamdo 760966.0
Xinhualu 758079.0
Nerima 742463.0
Guangshui 755910.0
Pietermaritzburg 750845.0
Baardheere 755500.0
Tlajomulco de Zúñiga 727750.0
Samarinda 753370.0
Changhua 750000.0
Sizhan 751389.0
Ciudad Guayana 751331.0
Cúcuta 750000.0
Dhūlia 750000.0
Burco 750211.0
Licheng 749522.0
Ōta-ku 737187.0
Thiruvananthapuram 743691.0
Tyumen 744554.0
Nampula 743000.0
Zaporizhzhia 741717.0
Kyaukse 741071.0
Chengguan 740435.0
Kumamoto 738385.0
Nehe 740000.0
Osogbo 731000.0
Cabinda 739182.0
Kermān 738374.0
Zunhua 737011.0
Rochester 737309.0
Valenzuela 714978.0
Orūmīyeh 736224.0
Wugang 734870.0
Shuangqiao 733000.0
Tshikapa 732000.0
São José dos Campos 729737.0
Comodoro Rivadavia 730266.0
Cagayan de Oro 728402.0
Tondo 654220.0
Langzhong 728935.0
Qian’an 728160.0
Lviv 724314.0
Sarasota 727388.0
Reynosa 725793.0
Santo André 721368.0
An Najaf 724700.0
Sagamihara 722973.0
Guli 723490.0
Mississauga 721599.0
Concepción 719944.0
Okayama 720043.0
Anlu 720000.0
Mwanza 706453.0
Fresno 719558.0
Changsha 717700.0
Torreón 716672.0
Shihezi 717000.0
Enugu 715774.0
Jaboatão 702621.0
Tulsa 715983.0
Yanggok 713321.0
Yatou 714211.0
Edogawa 697932.0
Allentown 714136.0
Ribeirão Prêto 711825.0
Xichang 712434.0
Latakia 700000.0
Bhiwandi 709665.0
City of Parañaque 689992.0
Dasmariñas 703141.0
Dayton 709300.0
Sahāranpur 705478.0
Warangal 704570.0
Soledad 698852.0
Osasco 694844.0
Dashiqiao 704891.0
Birmingham 704676.0
Nampo 703317.0
Shiliguri 701489.0
Banjarmasin 692793.0
Sha Tin 640000.0
Salem 693236.0
General Santos 697315.0
Cocody 692583.0
Ḩamāh 696863.0
Pendik 693599.0
Bacoor 664625.0
Vellore 696110.0
Shishi 693000.0
Guadalupe 691931.0
Adachi 682326.0
Qianxi 695947.0
Tolyatti 693072.0
Macau 568700.0
Bauchi 693700.0
Hamilton 693645.0
Łódź 690422.0
Miluo Chengguanzhen 692080.0
Gaizhou 691595.0
Karbalā’ 690100.0
Leling 689867.0
Jianshe 687130.0
Shizuoka 685589.0
Charleston 685517.0
Jingcheng 684360.0
Kochi 677381.0
Mar del Plata 682605.0
Cape Coral 682773.0
Tasikmalaya 678027.0
Rasht 679995.0
Xinmin 680000.0
Shanhu 679762.0
Zhongshu 679624.0
Gorakhpur 673446.0
Zaragoza 675301.0
Wrocław 672929.0
Acapulco de Juárez 673478.0
Bahār 673405.0
Kumul 673383.0
Murcia 672773.0
Pinghu 671834.0
Palermo 668405.0
Guankou 671200.0
Tlaquepaque 664193.0
Songyang 668592.0
Ch’ŏngjin 667929.0
Puyang Chengguanzhen 666322.0
Qionghu 667104.0
Zhaodong 666532.0
Narela 661994.0
Huambo 665564.0
Wenchang 664455.0
Villavicencio 664148.0
Shulan 663403.0
Tlalnepantla 653410.0
Catia La Mar 661897.0
Sargodha 659862.0
Al Hufūf 660788.0
Durango 654876.0
Jalingo 660213.0
Bouaké 659233.0
Mazatlán 658354.0
San Jose del Monte 651813.0
Ansan 652800.0
Abomey-Calavi 655965.0
Lingbao Chengguanzhen 656571.0
Hwasu-dong 655350.0
Sialkot City 655852.0
Huế 652572.0
Bulawayo 653337.0
Xiping 652604.0
Sanhe 652042.0
Ch’ŏnan 651661.0
Contagem 648766.0
Jieshou 650870.0
Selçuklu 648850.0
Ērer Sātā 649000.0
Honchō 641499.0
Düsseldorf 645923.0
Izhevsk 646277.0
Guntūr 647508.0
Guixi 647240.0
Sorocaba 644919.0
Yıldırım 643681.0
Petaling Jaya 638516.0
Tengyue 644765.0
Wuxue 644247.0
Rasūlpur 637272.0
Bhāvnagar 643365.0
Brahmapur 634220.0
Qufu 640498.0
Gaobeidian 640280.0
Ruiming 640600.0
Columbia 640502.0
Concord 640270.0
Noida 637272.0
Gold Coast 638090.0
Xinshi 636776.0
Ta‘izz 615467.0
Aracaju 632744.0
Jeonju 631532.0
Bhāngar 632107.0
Jin’e 633210.0
Barnaul 633301.0
Makati City 629616.0
Rotterdam 631155.0
Changping 614821.0
Benghazi 631555.0
Kryvyi Rih 629695.0
Ḩalwān 619293.0
Colorado Springs 628808.0
Suohe 626700.0
Chimalhuacán 614453.0
Xinxing 627475.0
Bhilai 625700.0
Mangalore 623841.0
Port-Bouët 618795.0
Zhuangyuan 626683.0
Glasgow 626410.0
Namangan 626120.0
Ulyanovsk 624518.0
Tân An 618984.0
Irkutsk 623736.0
Bhilai 624700.0
Nāgercoil 622759.0
Jos 622802.0
Pontianak 618388.0
Bazhou 622975.0
Turpan 622903.0
Villa Nueva 618397.0
Las Piñas City 606293.0
Springfield 620494.0
Knoxville 619925.0
Meihekou 618251.0
Jurong 617706.0
Feira de Santana 617528.0
Khabarovsk 616242.0
Zhugang 616346.0
Leipzig 615081.0
Xinji 615919.0
Serang 613356.0
Jambi 612162.0
Kandahār 614254.0
San Miguel de Tucumán 605767.0
Gothenburg 607882.0
Yaroslavl 608079.0
Baton Rouge 610751.0
Zhangshu 610424.0
Vladivostok 606589.0
Ogden 608259.0
Kuantan 607778.0
Raurkela 600000.0
Cuttack 606007.0
Ar Rayyān 605712.0
Haifa 600000.0
Malanje 604215.0
Bacolod 600783.0
Zhuozhou 603535.0
Grand Rapids 604311.0
Uberlândia 604013.0
Albany 604077.0
Tianchang 602840.0
Kawaguchi 593353.0
Itabashi 581337.0
Suginami-ku 583609.0
Cimahi 586580.0
Tuxtla 598710.0
Garoua 600000.0
Ḩafr al Bāţin 600000.0
Tumkūr 599078.0
Balikpapan 598043.0
Durban 595061.0
Kagoshima 593754.0
Al Ḩillah 594605.0
Makhachkala 592976.0
Sihui 593400.0
Irapuato 592953.0
Brampton 593638.0
Luocheng 591115.0
Mbale 586300.0
Pereira 590554.0
Bakersfield 590845.0
Uvira 590000.0
Dortmund 587696.0
Chuxiong 588620.0
Mission Viejo 588540.0
Zāhedān 587730.0
New Haven 587648.0
Shah Alam 584340.0
Wenlan 585976.0
Cuiabá 585367.0
Shangzhi 585386.0
Essen 582415.0
Botou 584308.0
Mymensingh 576722.0
Anyang 573296.0
Genoa 580097.0
Durgāpur 581409.0
Port Sudan 579942.0
Al Mafraq 580000.0
Puente Alto 573935.0
Dehra Dūn 578420.0
Aţ Ţā’if 579970.0
Wancheng 578600.0
Hachiōji 575721.0
Xiulin 577022.0
Fu’an 577000.0
Tomsk 572740.0
Tonalá 569913.0
Juiz de Fora 573285.0
Worcester 573573.0
Kolwezi 572942.0
Chāpra 567123.0
Bristol 567111.0
Luofeng 570898.0
Lingyuan 570660.0
Irbid 569068.0
Al Maḩallah al Kubrá 535278.0
Wencheng 568900.0
Bremen 566573.0
Ciudad Bolívar 567953.0
Orenburg 564773.0
Shenzhou 566087.0
Āsansol 563917.0
Kuiju 564501.0
Zhenzhou 564021.0
Surakarta 552118.0
Dresden 561922.0
Kolhāpur 561489.0
Benguela 561775.0
Ensenada 557430.0
Kemerovo 558973.0
Lanxi 560514.0
Dangyang 560000.0
Farīdpur 557632.0
Herāt 556205.0
Luanzhou 554315.0
Hamadān 554406.0
Novokuznetsk 552105.0
Nellore 547621.0
Palma 550000.0
Chiclayo 552508.0
Nānded 550439.0
Ajmer 551101.0
Al Ḩudaydah 548433.0
Kimhae 550758.0
Provo 551645.0
Rustenburg 549575.0
Amrāvati 549370.0
Poznań 546859.0
Huanghua 548507.0
Muntinlupa City 543445.0
Londrina 548249.0
Nansana 532800.0
Tabūk 547957.0
Heroica Matamoros 541979.0
Akron 546549.0
Samarkand 546303.0
Xingcheng 546176.0
Kaiyuan 545624.0
Hannover 542668.0
Valledupar 544134.0
Fengcheng 543933.0
Ixtapaluca 542211.0
Ghulja 542507.0
City of Calamba 539671.0
Ananindeua 540410.0
Xiangyang 541554.0
Fuding 542000.0
An Nāşirīyah 541600.0
Al Ḩillah 541034.0
Ibagué 541101.0
Ryazan 537622.0
Kassala 536009.0
Tripoli 530000.0
Chang’an 537500.0
Kōtō-ku 523117.0
Naberezhnyye Chelny 533839.0
Aksu 535657.0
Salta 535303.0
Astrakhan 532504.0
Gulbarga 533587.0
Cadaado 534023.0
Lyon 522969.0
Wuhai 532902.0
Mingguang 532732.0
Antwerp 529247.0
Yazd 529673.0
Touba 529176.0
Ardabīl 529374.0
Bīkaner 529007.0
Agartala 522613.0
Ndola 528330.0
Himeji 527596.0
Palm Bay 528322.0
Tultitlán de Mariano Escobedo 520557.0
Ailan Mubage 526745.0
Bandar ‘Abbās 526648.0
Bắc Ninh 520000.0
Ciudad Apodaca 523370.0
Santa Teresa del Tuy 525321.0
Maipú 521627.0
Penza 523726.0
Soacha 522442.0
Al Qaţīf 524182.0
Port Said 524433.0
Loni 516082.0
Yucheng 522878.0
Sevastopol 522057.0
Meknès 520428.0
Mixco 517505.0
Arāk 520944.0
Pohang 520305.0
Longzhou 520000.0
Anda 520000.0
Jinghong 519935.0
Sheffield 518090.0
Utsunomiya 518197.0
Suez 516959.0
Nuremberg 515543.0
Surrey 517887.0
Heshan 516500.0
Ujjain 515215.0
Jiaji 515700.0
Santa Marta 515556.0
Joinvile 515288.0
Beining 514898.0
Des Moines 514654.0
Hải Dương 507469.0
Carrefour 511345.0
Maturín 514046.0
Homyel’ 510300.0
Leicester 508916.0
Yanji 513072.0
Macapá 512902.0
Yicheng 512530.0
Ulhāsnagar 506098.0
Al ‘Āshir min Ramaḑān 511987.0
Lipetsk 510439.0
Al ‘Amārah 511500.0
Bhīlwāra 509483.0
Encheng 509700.0
Murrieta 509526.0
Aden 507355.0
Kitwe 504194.0
Matsuyama 506743.0
Jhānsi 507000.0
Pingtung 503530.0
Montería 505334.0
Nagqu 504838.0
Kimberley 500757.0
Jammu 502197.0
Ile-Ife 501952.0
Kirov 501468.0
Meicheng 500292.0

# HARJOITUS 2

In [11]:
# Harjoitus 2. SciKit-Learn ja hinnat.
# Asenna SciKit-Learn ja kirjoita koodia, joka käyttää lineaarista regressiota selvittämään hintojen kehityksen.
# Käytä opetusaineistona Hinnat.csv-tiedostoa.
# Mitä malli ennustaa hinnoiksi vuosille 2020-2023?
# Vinkki: tarvitset toimintoja "LinearRegression", "fit" ja "predict".

In [12]:
hinnat = pd.read_csv("Hinnat.csv")
hinnat

   vuosi  hinta
0   2011     40
1   2012     50
2   2013     55
3   2014     60
4   2015     65
5   2016     70
6   2017     75
7   2018     80
8   2019     90

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
X = hinnat[["vuosi"]]
y = hinnat["hinta"]

In [15]:
#type(X)

In [16]:
#type(y)

In [17]:
X

   vuosi
0   2011
1   2012
2   2013
3   2014
4   2015
5   2016
6   2017
7   2018
8   2019

In [18]:
y

0    40
1    50
2    55
3    60
4    65
5    70
6    75
7    80
8    90
Name: hinta, dtype: int64

In [19]:
reg_hinnat = LinearRegression().fit(X, y)

In [20]:
reg_hinnat.predict([[2020],[2021],[2022],[2023]])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([ 93.33333333,  99.        , 104.66666667, 110.33333333])

# HARJOITUS 4

In [21]:
import nltk
from nltk.corpus import treebank
syöte = input("Syötä englanninkielinen lause: ")
sanat = nltk.word_tokenize(syöte)
osat = nltk.pos_tag(sanat)
print(osat)
t = treebank.parsed_sents('wsj_0001.mrg')[0]
t.draw()

Syötä englanninkielinen lause:   NLTK is a leading platform for building Python programs to work with human language data

[('NLTK', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('leading', 'VBG'), ('platform', 'NN'), ('for', 'IN'), ('building', 'VBG'), ('Python', 'NNP'), ('programs', 'NNS'), ('to', 'TO'), ('work', 'VB'), ('with', 'IN'), ('human', 'JJ'), ('language', 'NN'), ('data', 'NNS')]

In [22]:
import nltk
print('Enter a sentence in english:')
sentence= input()
# sentence= input('Enter a sentence in english:')

Enter a sentence in english:

  NLTK is a leading platform for building Python programs to work with human language data

In [23]:
sentence

' NLTK is a leading platform for building Python programs to work with human language data'

In [24]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/kayttaja/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [25]:
tokens = nltk.word_tokenize(sentence)
tokens

['NLTK',
 'is',
 'a',
 'leading',
 'platform',
 'for',
 'building',
 'Python',
 'programs',
 'to',
 'work',
 'with',
 'human',
 'language',
 'data']

In [26]:
nltk.download('treebank')

[nltk_data] Downloading package treebank to
[nltk_data]     /Users/kayttaja/nltk_data...
[nltk_data]   Package treebank is already up-to-date!

True

In [27]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/kayttaja/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [28]:
from nltk import tag
tagged_sent = tag.pos_tag(tokens)
tagged_sent

[('NLTK', 'NNP'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('leading', 'VBG'),
 ('platform', 'NN'),
 ('for', 'IN'),
 ('building', 'VBG'),
 ('Python', 'NNP'),
 ('programs', 'NNS'),
 ('to', 'TO'),
 ('work', 'VB'),
 ('with', 'IN'),
 ('human', 'JJ'),
 ('language', 'NN'),
 ('data', 'NNS')]